apiVersion: v1
kind: Pod
metadata:
  name: structured-data-logger-server
spec:
  restartPolicy: on-failure
  containers:
    - name: xtdb
      image: ghcr.io/xtdb/xtdb:2.1.0
      volumeMounts:
        - mountPath: /var/lib/xtdb
          name: xtdb-data
    - name: api
      image: localhost/structured-data-logger-server:latest
      ports:
        - containerPort: 6000
          hostIp: 127.0.0.1
          hostPort: 6000
      env:
        - name: port
          value: 6000
        - name: dbhost
          value: xtdb
  volumes:
    - name: xtdb-data
      persistentVolumeClaim:
        claimName: structured-data-logger-xtdb-data
